version: '2'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    volumes:
      - ./policy/filtering.rego:/policy.rego
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy.rego"

  sql_clinical:
    build: ./sql_clinical
    volumes:
      - ./testdata/sql_clinical.sqlite:/sql_clinical.sqlite
      - ./testdata/sql_clinical.log:/sql_clinical.log
    command:
      - "--logfile=/sql_clinical.log"
      - "--database=/sql_clinical.sqlite"
      - "--loglevel=INFO"
    ports:
      - "3000:3000"
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/filtering/allow
    links:
      - opa

#  clinical_service:
#    build: ./clinical_service
#    volumes:
#      - ./testdata/clinical_service.log:/clinical_service.log
#    command:
#      - "--logfile=/clinical_service.log"
#      - "--loglevel=INFO"
#    ports:
#      - "4000:4000"
#    links:
#      - sql_clinical