#!/bin/bash

export ALICE_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU"
export BOB_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjpmYWxzZSwiZW50aXRsZW1lbnRzIjpbInByaW1hcnkiLCJzZWNvbmRhcnlBIl19.5E1py4p10Aul0eI9XgPgKXDL5te9fd4_D_1OpDTPwBg"
export CAROL_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg"
export FRANK_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOltdfQ.S-Wo0UGlpKLTvibHjkppER2J4H6HnR1i7GYjNwBZjm0"